import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}


// import Head from 'next/head';
// import type { AppProps } from 'next/app'
// import { ThemeProvider } from '@mui/material/styles';
// import CssBaseline from '@mui/material/CssBaseline';
// import { CacheProvider, EmotionCache } from '@emotion/react';
// import theme from './theme';
// import createEmotionCache from './createEmotionCache';

// const clientSideEmotionCache = createEmotionCache();
// interface MyAppProps extends AppProps {
//   emotionCache?: EmotionCache;
//   children: React.ReactNode
// }

// function MyApp(props: MyAppProps) {
//   const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;
//   return (
//     <html lang="ja">    <CacheProvider value={emotionCache}>
//       <Head>
//         <meta name="viewport" content="initial-scale=1, width=device-width" />
//       </Head>
//       <ThemeProvider theme={theme}>
//         <CssBaseline />
//         <Component {...pageProps} />
//       </ThemeProvider>
//     </CacheProvider>
//     </html>

//   )
// }

// export default MyApp
